# Generated by Django 5.2.6 on 2025-09-23 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premise', models.CharField(max_length=255)),
                ('incident_type', models.CharField(choices=[('Mantrap', 'Mantrap'), ('Power Failure', 'Power Failure'), ('Door Jam', 'Door Jam')], max_length=50)),
                ('status', models.CharField(default='Detected', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
