# Generated by Django 5.2.6 on 2025-09-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
