# Generated by Django 5.2.6 on 2025-09-24 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_incident_resolved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('Alert', 'Alert')], default='Normal', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='attended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('premise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='dashboard.premise')),
            ],
        ),
    ]
